spring:
  mongodb:
    uri: mongodb+srv://Rohit:7244@cluster0.0jnpmh7.mongodb.net/?appName=Cluster0
    database: journaldb
  data:
    redis:
      url: redis://default:MrBJnBJxd0IABGOckJpTwcHTKjppuzmT@redis-11993.c330.asia-south1-1.gce.cloud.redislabs.com:11993
    mongodb:
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rohitkoshyari7244@gmail.com
    password: fxcr aedk yhkv eqfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



#server:
#  port: 8081
#  servlet:
#    context-path: /journal